### ISSUE TITLE
Can't boot on emmc

### ISSUE THREAD

**Issue by JyuHo** [mrfixit2001/recalbox_rockpro64#1]
Hello,
I could test the alpha version on SD card and it works very well (emulators, sound, kodi, bluetooth, etc ...)
On the other hand when one installs on the emmc, it does not boot.
I managed to boot by putting the .dtb present in the iso 0.7.9 of ayufan but we lose the sound,
either by hdmi or jack 3.5. 
So much for my return and the problems encountered. If ik was also able to put sources on your git it would be a plus to be able to create PRs.

Jyu

**Comment by mrfixit2001** [comment]
Thank you for letting me know!!

Have confirmed that on the new beta release eMMC booting is not an issue. It works on both the eMMC 4 and 5 chips. Closing.
