### ISSUE TITLE
Question - Can this play mario party 1-7 without any issues?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mrfixit2001/recalbox_rockpro64#2]
I am trying to make an emulator box that serves one purpose - plays mario party 1-7 perfectly. I don't expect wii support yet but if I can play 8-9 great its not a deal breaker though. I just want 1-7 with no stutters or lag or graphics flicker/distortion and if this can do this on a rockpro64 I will definitely pick one up. I do not consider first time caching to be considered actually stutter.

**Comment by mrfixit2001** [comment]
Recalbox does not currently have wii/gamecube, so I believe Mario Party 4-7 are all on unsupported systems. 
Mario Party 1-3 for N64 all play very well, and will continue to play better as improvements are made in the emulators.

**Comment by P3rf3ctXZer0** [comment]
If you remember my name and things change let me know.
