### ISSUE TITLE
SNES-style USB controller does not work, cannot access emulator menus

### ISSUE THREAD

**Issue by wesm** [mrfixit2001/recalbox_rockpro64#3]
I just flashed the latest build on a brand new rockpro64, I tried out my iBuffalo Classic USB gamepad which I've used without incident on rpi3/retropie in the past, and I found that it does not work in any emulator save for the start and A buttons. Ran through controller configuration multiple times to no avail. I tried my 8bitdo SN30 Pro bluetooth controller and found the same behavior; the bluetooth also seems to disconnect randomly. 

With a keyboard attached I've been unable to bring up the in-emulator menu either. Not sure what I'm doing wrong but let me know if there's some standard troubleshooting that might make things work

**Comment by nunyabisnas** [comment]
i have the same issues with the ibuffalo classic, 8bitdo m30, and ps3 wired controllers. the controllers will configure without issue in the main interface but the configuration will not be applied when an emulator core is loaded. the issue exists on both the mrifxit2001 rock64 and rockpro64 builds but not with any of the other recalbox builds, for example the recalbox builds for raspberry pi handle these controllers fine.

this issue effectively makes the mrfixit2001 builds useless if you don't keep a keyboard attached. with a keyboard, if you can manage to open the retroarch menu, you can manually map the buttons for each controller whenever an emulator core loads, but i haven't invested sufficient time to make the mapping persist.

**Comment by JoeOsborn** [comment]
I think I’ve seen the same issue with the PS3 controllers in wired mode, as well as strange mappings for the Xbox 360 wired controller that are inconsistent between emulationstation and retroarch.  I don’t have other controllers or recalbox machines to test with unfortunately.

**Comment by mrfixit2001** [comment]
I have a new release incoming in the new recalbox-rockchip repo.
I have been testing with my 8bitdo NES30 Pro and it pairs and works well inside all games. You may want to set the controller you wish to use as P1 in the menu as well, which can sometimes help if you have multiple controllers connected.
