### ISSUE TITLE
Not saving settings?

### ISSUE THREAD

**Issue by Maxpako** [mrfixit2001/recalbox_rockpro64#4]
Hi,

I've been testing this image in EMMC of 16 GB and seems it's not saving data... for example:
1- When setting language to Spanish, it requests to reboot, and once restarted it's still in english
2- On boots, it always asks for controllers setup, always.
3- The brand new roshambo controllers (https://www.cloudmedia.com/?product=roshambo-game-pad-x-2) doesn't have "hotkey" button, so don't know what kind of button/combination should I set (in my case I set Select, but don't know what's that for).
4- Kodi seems not starting (left 5 minutes on Kodi screen, nothing else showing up)
5- When looking at the EMMC (16GB one), there are 12GB unassigned, am I missing a partition?
I've chedked one rom from SNES and seems working, however not playable due to (seems) this: https://github.com/mrfixit2001/recalbox_rockpro64/issues/3

By the way, the CPU fan wasn't running either, I had to activate it with:
`echo "150" > /sys/class/hwmon/hwmon0/pwm1 (on the startup script)`

Thanks in advance!

**Comment by Maxpako** [comment]
> 3- The brand new roshambo controllers (https://www.cloudmedia.com/?product=roshambo-game-pad-x-2) doesn't have "hotkey" button, so don't know what kind of button/combination should I set (in my case I set Select, but don't know what's that for).

On Windows 10 May update, those controllers are recognized as (surprisingly) Xbox 360 Controller for Windows, and the button between Select and Start works as the Xbox button.

Can it be changed somehow in the options so that the controller is recognized differently?

**Comment by Maxpako** [comment]
Update, problem number 1 is solved, I've re-flashed the emmc, and now it saves the changes 👍

**Comment by mrfixit2001** [comment]
Thanks for the report! New release incoming in the new repo - fully updated with latest recalbox codes. I've added an option in emulationstation under system settings to enable the fan now.
