### ISSUE TITLE
HOW TO fix Wifi on RockPro64 - Recalbox OS and upload roms on SSD External

### ISSUE THREAD

**Issue by Gouki83** [mrfixit2001/recalbox_rockpro64#6]
Hi everyone, 

I'm trying to understand few things on the RockPro 64 board, I've tried on the Pine64 forum and no luck but a user (evilbunny) suggested me to try here:

 I have a Rockpro64 with a Roshambo case and recalbox OS installed, I've tried a generic WiFi module 802,11n but when I switch enable WiFi it doesn't do anything.. any idea how can I get it to work? I know there is a dedicated module but I want to avoid to spend extra money. I have tried running the terminal remotely, but no luck, don't really know what commands I should run, will be the same case with a generic Bluetooth stick? 
And the other thing is how can I upload ROMs in the external SSD as i bought the mini cartridge as well. When I move ROMs is like moving them in mini SD, do i need to use a converter and plug the SSD to my PC to transfer files? (haven't tried as I don't have a cable yet)
I have also plugged a IBuffalo controller (SNES clone usb controller) it works fine in Recalbox, configured correctly, but when I launch a game it doesn't work properly, some buttons don't respond, when I launch Retroarch in game I can manage to configure the controller with a keyboard and after that works fine for that emulator only in game tough (have to press reset to exit) and I have to to this each time in RetroArch for all the platforms, is there any fix?  

Thanks in advance :)

**Comment by mrfixit2001** [comment]
Thanks for reaching out. A few tips - 
First make sure the wifi module is connected prior to powering on. 
Second - make sure the wifi module is supported by the linux kernel (unplug it and plug it back in and then check dmesg to see if it successfully identifies it)
Lastly - I have a new release incoming in the new recalbox-rockchip repo that is fully updated with recalbox master and will hopefully address any further issues
